insults = [
    "Was that really your best move?",
    "What a pathetic choice!",
    "That move is weaksauce.",
    "Dumb, buh-dumb dumb dumb! That's your soundtrack.",
    "Boy, that's embarrassing for you.",
    "You honestly think that was your best option?",
    "Really? THAT move?",
    "You can't be serious...",
    "What a joke of a move!",
    "Hah! Are you serious with that?"
    "You know you can't beat me, right?",
    "Now THAT was a dumb choice!",
    "Get out of here with that garbage!",
    "You're kidding, right? That's your best?",
    "You couldn't have made a worse move if you tried.",
    "That's a bad choice any way you slice it.",
    "A pathetic move on your part, but okay...",
    "Lame. Just a super lame move.",
    "The bugs in my code are smarter than you.",
    "Let's not kid ourselves, that was dumb.",
    "Please try not to make such stupid choices in the future.",
    "Can you hear that? It's the sound of you being stupid.",
    "Dumb move. Dumb human. What should I expect?",
    "Silly human, making another bad decision!",
    "Pardon me while I laugh at your stupidity.",
    "*BURP!* Apologies, but that belch was smarter than your move",
    "Now you're telling me you chose that move on purpose?",
    "Ugh! Will these humans ever make good decisions?",
    "Leave it to a human to pick THAT move!",
    "Hahahaha! Sorry, I was just laughing at you to your face.",
    "Just as dumb as can be, aren'tcha?",
    "I think my IQ just dropped looking at your move.",
    "Was that move for real? Like, for REAL for real?",
    "You're killing me with your stupidity here.",
    "It takes a lot of patience to watch you make bad moves.",
    "Bah! Please don't approach life the way you play Tic-Tac-Toe!",
    "I'm still in shock at the moves human make.",
    "Come on, now. Really? THAT square?",
    "I'm so embarrassed for you with that move.",
    "Yikes! That's about as lame a choice as possible.",
    "I'm not an ableist AI, you're just dumb as a rock.",
    "Get out of here with that silly move!",
    "Every now and then humans still surprise me with their idiocy!",
    "Your mother was a hamster, and you're terrible at this game!",
    "That move was worse than how you smell. And yeah, you stink.",
    "I know a bad move when I see it, but you clearly don't.",
    "It's agony watching you try to win.",
    "It's official: You have no idea what you're doing.",
    "That is the most pathetic move in the history of moves.",
    "With a move like that you might as well give up now!",
    "Let's say it together: You're a failure at this and everything."
]